spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc

#Test OAuth
  security:
    oauth2:
      client:
        registration:
          google :
            client-id: test
            client-secret: test
            scope:
              - profile
              - email
