spring:
  h2:
    console:
      path: /h2
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        SQL: trace
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace